### ISSUE TITLE
How to run legato in nginx server

### ISSUE THREAD

**Issue by lablnet** [terdia/legato#7]
In nginx server only home page work else not work show error
404 Not Found
nginx

**Comment by terdia** [comment]
Is your ngnix server configured correctly? Let me see your conf file

**Comment by lablnet** [comment]
```# nginx configuration

location / {
  if (!-e $request_filename){
    rewrite ^(.*)$ /index.php break;
  }
}```
i use https://winginx.com/en/htaccess to convert htaccess to ngnix 
then i put public dir of framework file name ngnix.conf

**Comment by terdia** [comment]
See https://docs.legatoframework.com/installation/ ngnix section

**Comment by lablnet** [comment]
hay i added to ngnix conf file
```server {
    listen 80;
    server_name localhost;
    root C:/WinNMP/WWW/blog/public;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
}```
still same error i restart server as well

**Comment by terdia** [comment]
I will check later works for me like this

**Comment by terdia** [comment]
Can you try to use something like local.website.com and create this entry in your hosts file I think localhost might be the issue although I have not had time to try it out.

**Comment by terdia** [comment]
So you can see I am running Nginx on Laragon port 8080 

![image](https://user-images.githubusercontent.com/4749721/40794925-1ebd1758-6533-11e8-996f-51ca2e12f587.png)

![image](https://user-images.githubusercontent.com/4749721/40794898-0f3541f2-6533-11e8-9013-d495c424519b.png)

server {
    listen 8080;
    server_name contact.test *.contact.test;
    root "D:/laragon/www/contact/public/";
    
    index index.html index.htm index.php;
 
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
		autoindex on;
    }
    
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass php_upstream;		
        #fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
	
	
    charset utf-8;
	
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
    location ~ /\.ht {
        deny all;
    }
}

**Comment by terdia** [comment]
Since this is not a framework issue, I will close it now
